CREATE DATABASE [IF NOT EXISTS] timeIt;
USE timeIt;

CREATE TABLE timers(
  id SMALLINT NOT NULL AUTO_INCREMENT,
  title VARCHAR(255) UNIQUE NOT NULL,
  hours INT (6) NOT NULL,
  minutes INT (2) ZEROFILL NOT NULL,
  seconds INT (2) ZEROFILL NOT NULL,
  PRIMARY KEY (id)
);